### ISSUE TITLE
track_request is not working

### ISSUE THREAD

**Issue by zooba** [Microsoft/AppInsights-Python#12]
I've been trying out `WSGIApplication` and I'm not seeing any request messages being tracked. If I replace the call to `track_request` with `track_event` and make a string out of all the contents, then it comes through fine.

It may just be that AppInsights isn't running well right now (neither is Azure storage...), but simple events seems to be coming through eventually. Is there possibly something failing during serialization or not matching what the service expects and being rejected?

**Comment by BogdanBe** [comment]
Looking into it.

**Comment by BogdanBe** [comment]
The duration field was being serialized as a number (the raw number of milliseconds). The server now accepts a string of form ```[ddd.]hh:mm:ss.fffffff```. This has been addressed with the code in pull request #14.

**Comment by BogdanBe** [comment]
This is now fixed. A new version of the package has been published to PyPI: version 0.8.1
