### ISSUE TITLE
Description is not rendered correctly on PyPI

### ISSUE THREAD

**Issue by zooba** [Microsoft/AppInsights-Python#6]
The PyPI page is not rendering the long description correctly. This normally happens because of a markup error somewhere in the description, and PyPI does not help.

The [distutils docs](https://docs.python.org/3/distutils/packageindex.html#pypi-package-display) suggest a way to check for markup errors.

**Comment by BogdanBe** [comment]
Thanks for the pointer. I've fixed all descriptions found on PyPI. I've also fixed the checked in version (on the same branch as the one used for the instrumentation key change).

**Comment by BogdanBe** [comment]
Fixed in https://github.com/Microsoft/AppInsights-Python/pull/9
