### ISSUE TITLE
TelemetryClient constructor taking instrumentation key?

### ISSUE THREAD

**Issue by zooba** [Microsoft/AppInsights-Python#7]
It would be nice to be able to construct a TelemetryClient with just a key, rather than having to remember about setting it via context.

```
tc = TelemetryClient('12345678-1234-1234-1234567890')
```

Since the first parameter can currently only be a TelemetryChannel, it seems easy enough to test for that type.

Maybe there's some reason why it makes sense to disallow this, but I can't think of it myself.

**Comment by BogdanBe** [comment]
The instrumentation key is always required so there is no good reason why we would want to create a client that doesn't have have one. As such we will add an additional (required) parameter to the ctor of `TelemetryClient`

To maintain backwards compatibility, we will test the first parameter for the `TelemetryChannel` type and we will not raise an exception in this case.

**Comment by BogdanBe** [comment]
Fixed in https://github.com/Microsoft/AppInsights-Python/pull/9
